{{
    config(
        materialized='table',
        tags = ["raw","batting","bowling"]
    )
}}

with carrier as(
    SELECT 
        {{ dbt_utils.star(from=ref('stg_raw_playercarrier_stats'), except=["RUNS_MADE", "BALLS_TAKEN", "SIXES_HITTEN", "FOURS_HITTEN", "BATTING_STRIKE_RATE", "BATTING_AVG", "CATCHES", "BOWLING_AVERAGE", "BOWLER_ECONOMY", "BOWLER_STRIKE_RATE"]) }}
        , (CASE WHEN RUNS_MADE IS NULL THEN 0 ELSE 1 END) AS RUNS_MADE
        , (CASE WHEN BALLS_TAKEN IS NULL THEN 0 ELSE 1 END) AS BALLS_TAKEN
        , (CASE WHEN SIXES_HITTEN IS NULL THEN 0 ELSE 1 END) AS SIXES_HITTEN
        , (CASE WHEN FOURS_HITTEN IS NULL THEN 0 ELSE 1 END) AS FOURS_HITTEN
        , (CASE WHEN BATTING_STRIKE_RATE IS NULL THEN 0 ELSE 1 END) AS BATTING_STRIKE_RATE
        , (CASE WHEN BATTING_AVG IS NULL THEN 0 ELSE 1 END) AS BATTING_AVG
        , (CASE WHEN WICKETS_TAKEN IS NOT NULL AND BOWLING_AVERAGE IS NULL THEN 0 ELSE 1 END) AS BOWLING_AVERAGE
        , (CASE WHEN OVERS_DELIVERED IS NOT NULL AND BOWLER_ECONOMY IS NULL THEN 0 ELSE 1 END) AS BOWLER_ECONOMY
        , (CASE WHEN WICKETS_TAKEN IS NOT NULL AND BOWLER_STRIKE_RATE IS NULL THEN 0 ELSE 1 END) AS BOWLER_STRIKE_RATE
        , (CASE WHEN CATCHES IS NULL THEN 0 ELSE 1 END) AS CATCHES
    FROM {{ ref('stg_raw_playercarrier_stats') }}
)

SELECT * FROM carrier