{{
    config(
        materialized='table',
        tags = ["raw","batting","bowling"]
    )
}}

with carrier as(
    SELECT 
        {{ dbt_utils.star(from=ref('stg_raw_playercarrier_stats'), except=["RUNS_MADE", "BALLS_TAKEN", "FIFTIES", "HUNDREDS", "SIXES_HITTEN", "FOURS_HITTEN", "BATTING_STRIKE_RATE", "BATTING_AVG", "NOT_OUTS", "OVERS_DELIVERED", "BALLS_DELIVERED", "RUNS_CONCEEDED", "WICKETS_TAKEN", "CATCHES", "BOWLING_AVERAGE", "BOWLER_ECONOMY", "BOWLER_STRIKE_RATE", "FOUR_WICKETS_HOUL", "FIVE_WICKETS_HOUL", "STUMPINGS"]) }}
        , (CASE WHEN RUNS_MADE IS NULL THEN 0 ELSE RUNS_MADE END) AS RUNS_MADE
        , (CASE WHEN BALLS_TAKEN IS NULL THEN 0 ELSE BALLS_TAKEN END) AS BALLS_TAKEN
        , (CASE WHEN FIFTIES IS NULL THEN 0 ELSE FIFTIES END) AS FIFTIES
        , (CASE WHEN HUNDREDS IS NULL THEN 0 ELSE HUNDREDS END) AS HUNDREDS
        , (CASE WHEN SIXES_HITTEN IS NULL THEN 0 ELSE SIXES_HITTEN END) AS SIXES_HITTEN
        , (CASE WHEN FOURS_HITTEN IS NULL THEN 0 ELSE FOURS_HITTEN END) AS FOURS_HITTEN
        , (CASE WHEN BATTING_STRIKE_RATE IS NULL THEN 0.00 ELSE BATTING_STRIKE_RATE END) AS BATTING_STRIKE_RATE
        , (CASE WHEN BATTING_AVG IS NULL THEN 0.00 ELSE BATTING_AVG END) AS BATTING_AVG
        , (CASE WHEN NOT_OUTS IS NULL THEN 0 ELSE NOT_OUTS END) AS NOT_OUTS
        , (CASE WHEN OVERS_DELIVERED IS NULL THEN 0 ELSE OVERS_DELIVERED END) AS OVERS_DELIVERED
        , (CASE WHEN BALLS_DELIVERED IS NULL THEN 0 ELSE BALLS_DELIVERED END) AS BALLS_DELIVERED
        , (CASE WHEN RUNS_CONCEEDED IS NULL THEN 0 ELSE RUNS_CONCEEDED END) AS RUNS_CONCEEDED
        , (CASE WHEN WICKETS_TAKEN IS NULL THEN 0 ELSE WICKETS_TAKEN END) AS WICKETS_TAKEN
        , (CASE WHEN WICKETS_TAKEN IS NOT NULL AND BOWLING_AVERAGE IS NULL THEN 0.00 ELSE BOWLING_AVERAGE END) AS BOWLING_AVERAGE
        , (CASE WHEN OVERS_DELIVERED IS NOT NULL AND BOWLER_ECONOMY IS NULL THEN 0.00 ELSE BOWLER_ECONOMY END) AS BOWLER_ECONOMY
        , (CASE WHEN WICKETS_TAKEN IS NOT NULL AND BOWLER_STRIKE_RATE IS NULL THEN 0.00 ELSE BOWLER_STRIKE_RATE END) AS BOWLER_STRIKE_RATE
        , (CASE WHEN FOUR_WICKETS_HOUL IS NULL THEN 0 ELSE FOUR_WICKETS_HOUL END) AS FOUR_WICKETS_HOUL
        , (CASE WHEN FIVE_WICKETS_HOUL IS NULL THEN 0 ELSE FIVE_WICKETS_HOUL END) AS FIVE_WICKETS_HOUL
        , (CASE WHEN CATCHES IS NULL THEN 0 ELSE CATCHES END) AS CATCHES
        , (CASE WHEN STUMPINGS IS NULL THEN 0 ELSE STUMPINGS END) AS STUMPINGS
    FROM {{ ref('stg_raw_playercarrier_stats') }}
)

SELECT * FROM carrier