{{
    config(
        materialized='table',
        tags = ["raw","carrier","batting","raw_carrier"]
    )
}}

WITH batting as(
    SELECT
        PLAYERID::NUMBER AS PLAYER_ID
        , PLAYERNAME AS PLAYER_NAME
        , YEAR AS YEAR_TYPE
        , TEAMNAME AS TEAM_NAME
        , MATCHES::NUMBER AS MATCHES
        , INNINGS::NUMBER AS INNINGS
        , (CASE WHEN RUNS IS NULL THEN 0 ELSE RUNS END)::NUMBER AS RUNS_MADE
        , (CASE WHEN BALLS IS NULL THEN 0 ELSE BALLS END)::NUMBER AS BALLS_TAKEN
        , (CASE WHEN HIGHESTSCORE LIKE '%*' THEN REPLACE(HIGHESTSCORE,'*','') ELSE HIGHESTSCORE END)::NUMBER AS HIGHEST_SCORE
        , FIFTIES::NUMBER AS FIFTIES
        , HUNDREDS::NUMBER AS HUNDREDS
        , (CASE WHEN SIXES IS NULL THEN 0 ELSE SIXES END)::NUMBER AS SIXES_HITTEN
        , (CASE WHEN FOURS IS NULL THEN 0 ELSE FOURS END)::NUMBER AS FOURS_HITTEN
        , (CASE WHEN STRIKERATE IS NULL THEN 0 ELSE STRIKERATE END)::NUMBER AS BATTING_STRIKE_RATE
        , (CASE WHEN BATTINGAVG IS NULL THEN 0 ELSE BATTINGAVG END)::NUMBER AS BATTING_AVG
        , NOTOUTS::NUMBER AS NOT_OUTS
        , STATSTYPE AS STATS_TYPE
        , (CASE WHEN CATCHES IS NULL THEN 0 ELSE CATCHES END)::NUMBER AS CATCHES
        , STUMPINGS::NUMBER AS STUMPINGS
        , CLIENTPLAYERID::NUMBER AS CLIENT_PLAYER_ID
        , FILENAME AS FILE_NAME
        , CONVERT_TIMEZONE('UTC', 'Asia/Kolkata', LOAD_TIMESTAMP)::TIMESTAMP_NTZ AS SOURCE_LOAD_TIMESTAMP
        , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS _inserted_at_
    FROM {{ source('ipl_carrier_database','batting')}}
    WHERE PLAYERID IS NOT NULL
    ORDER BY PLAYER_ID
)

SELECT * FROM batting