{{
    config(
        materialized='table',
        tags = ["raw","carrier","batting","raw_carrier"]
    )
}}

WITH batting as(
    SELECT
        PLAYERID::NUMBER AS PLAYER_ID
        , PLAYERNAME AS PLAYER_NAME
        , YEAR AS YEAR_TYPE
        , TEAMNAME AS TEAM_NAME
        , MATCHES::NUMBER AS MATCHES
        , INNINGS::NUMBER AS INNINGS
        , RUNS::NUMBER AS RUNS_MADE
        , BALLS::NUMBER AS BALLS_TAKEN
        , (CASE WHEN HIGHESTSCORE LIKE '%*' THEN REPLACE(HIGHESTSCORE,'*','') ELSE HIGHESTSCORE END)::NUMBER AS HIGHEST_SCORE
        , FIFTIES::NUMBER AS FIFTIES
        , HUNDREDS::NUMBER AS HUNDREDS
        , SIXES::NUMBER AS SIXES_HITTEN
        , FOURS::NUMBER AS FOURS_HITTEN
        , STRIKERATE::NUMBER AS BATTING_STRIKE_RATE
        , BATTINGAVG::NUMBER AS BATTING_AVG
        , NOTOUTS::NUMBER AS NOT_OUTS
        , STATSTYPE AS STATS_TYPE
        , CATCHES::NUMBER AS CATCHES
        , STUMPINGS::NUMBER AS STUMPINGS
        , CLIENTPLAYERID::NUMBER AS CLIENT_PLAYER_ID
        , FILENAME AS FILE_NAME
        , CONVERT_TIMEZONE('UTC', 'Asia/Kolkata', LOAD_TIMESTAMP)::TIMESTAMP_NTZ AS SOURCE_LOAD_TIMESTAMP
        , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS _inserted_at_
    FROM {{ source('ipl_carrier_database','batting')}}
    WHERE PLAYERID IS NOT NULL
    ORDER BY PLAYER_ID
)

SELECT * FROM batting