{{
    config(
        materialized='table',
        tags = ["raw","carrier","bowling","raw_carrier","inactive"]
    )
}}

with bowling as(
    SELECT
        PLAYERID::NUMBER AS PLAYER_ID
        , PLAYERNAME AS PLAYER_NAME
        , YEAR AS YEAR_TYPE
        , TEAMNAME AS TEAM_NAME
        , MATCHES::NUMBER AS MATCHES
        , INNINGS::NUMBER AS INNINGS
        , OVERS::NUMBER AS OVERS_DELIVERED
        , BALLS::NUMBER AS BALLS_DELIVERED
        , RUNS::NUMBER AS RUNS_CONCEEDED
        , WICKETS::NUMBER AS WICKETS_TAKEN
        , BBM AS BEST_BOWLING_FIGURE
        , (CASE WHEN WICKETS_TAKEN IS NOT NULL AND AVERAGE IS NULL THEN 0 ELSE AVERAGE END)::NUMBER AS BOWLING_AVERAGE
        , (CASE WHEN OVERS_DELIVERED IS NOT NULL AND ECON IS NULL THEN 0 ELSE ECON END)::NUMBER AS BOWLER_ECONOMY
        , (CASE WHEN WICKETS_TAKEN IS NOT NULL AND STRIKERATE IS NULL THEN 0 ELSE STRIKERATE END)::NUMBER AS BOWLER_STRIKE_RATE
        , FOURWKTS::NUMBER AS FOUR_WICKETS_HOUL
        , FIVEWKTS::NUMBER AS FIVE_WICKETS_HOUL
        , STATSTYPE AS STATS_TYPE
        , FILENAME AS FILE_NAME
        , CONVERT_TIMEZONE('UTC', 'Asia/Kolkata', LOAD_TIMESTAMP)::TIMESTAMP_NTZ AS SOURCE_LOAD_TIMESTAMP
        , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ AS _inserted_at_
    FROM {{ source('ipl_carrier_database','bowling')}}
    WHERE PLAYERID IS NOT NULL
    ORDER BY PLAYER_ID
)

SELECT * FROM bowling